#!/usr/bin/ash

#
# init script for anvl installer initramfs generated by mkinitcpio
#
# Loosely based on the script at:
# http://jootamam.net/howto-initramfs-image.htm
#

#
# Set up initial mounts
#
mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
mount -t devtmpfs dev /dev -o mode=0755,nosuid
mount -t tmpfs run /run -o nosuid,nodev,mode=0755
#mount -t proc none /proc
#mount -t sysfs none /sys
mount -t configfs none /sys/kernel/config
#mount -t devtmpfs none /dev/
#mkdir /dev/pts
#mount -t devpts none /dev/pts

modprobe -ab evdev twl4030_wdt rtc_twl pwm_twl autofs4 \
  mwifiex_sdio leds_pca963x ledtrig_timer bq24190_charger
sleep 1

echo "Starting init script with cmdline options: $@"

#
# Function for initializing USB composite gadget
# Based on the sample configuration at:
# https://wiki.tizen.org/wiki/USB/Linux_USB_Layers/Configfs_Composite_Gadget/Usage_eq._to_g_multi.ko
#
start_usb() {
	file0=$1
	omap_dieid=$2

	echo "Starting USB gadgets..."

	modprobe -ab usb_f_rndis usb_f_mass_storage usb_f_ecm usb_f_acm \
	   musb_hdrc phy_twl4030_usb omap2430
	sleep 1

	old_pwd=$(pwd)
	mkdir /sys/kernel/config/usb_gadget/g1
	cd /sys/kernel/config/usb_gadget/g1

	echo 0x0106 > idProduct
	echo 0x1d6b > idVendor
	echo 0x0100 > bcdDevice
	echo 0x0200 > bcdUSB

	mkdir strings/0x409
	echo $omap_dieid > strings/0x409/serialnumber
	echo "Anvl" > strings/0x409/manufacturer
	echo "Multi Gadget" > strings/0x409/product

	mkdir functions/mass_storage.0
	echo $file0 > functions/mass_storage.0/lun.0/file
	mkdir functions/acm.0
	#mkdir functions/ecm.0
	#mkdir functions/rndis.0

	mkdir -p configs/c.1/strings/0x409
	echo 500 > configs/c.1/MaxPower
	echo "Conf 1" > configs/c.1/strings/0x409/configuration
	#ln -s functions/ecm.0 configs/c.1
	ln -s functions/acm.0 configs/c.1
	ln -s functions/mass_storage.0 configs/c.1

	#mkdir -p configs/c.2/strings/0x409
	#echo 500 > configs/c.2/MaxPower
	#echo "Conf 2" > configs/c.2/strings/0x409/configuration
	#ln -s functions/rndis.0 configs/c.2
	#ln -s functions/acm.0 configs/c.2
	#ln -s functions/mass_storage.0 configs/c.2

	echo musb-hdrc.0.auto > /sys/kernel/config/usb_gadget/g1/UDC
	cd $old_pwd
}

blink_leds() {
	color=$1
	on=$2
	off=$3
	led="/sys/class/leds/pca963x:"
	red="${led}red/brightness"
	green="${led}green/brightness"
	blue="${led}blue/brightness"

	echo 0 > $red
	echo 0 > $green
	echo 0 > $blue

	case $color in
	red)
		echo 30 > $red ;;
	green)
		echo 30 > $green ;;
	blue)
		echo 30 > $blue ;;
	cyan)
		echo 30 > $green
		echo 30 > $blue ;;
	magenta)
		echo 30 > $red
		echo 30 > $blue ;;
	yellow)
		echo 30 > $red
		echo 30 > $green ;;
	orange)
		echo 40 > $red
		echo 10 > $green ;;
	none)
		echo none > "${led}red/trigger"
		echo none > "${led}green/trigger"
		echo none > "${led}blue/trigger"
		return 0 ;;
	*)
		echo 30 > $red
		echo 30 > $green
		echo 30 > $blue ;;
	esac

	echo timer > "${led}red/trigger"
	echo timer > "${led}green/trigger"
	echo timer > "${led}blue/trigger"
	echo $on   > "${led}red/delay_on"
	echo $off  > "${led}red/delay_off"
}

#
# Run some sanity checks on hardware
#
check_block_device() {
	if [ -b $1 ]; then
		return 0
	fi
	return 1
}

#
# Try not to touch the external MMC card
#
if ls /dev/mmcblk1 > /dev/null 2>&1; then
	emmc=/dev/mmcblk1
else
	emmc=/dev/mmcblk0
	echo "/dev/mmcblk1 not found, assuming eMMC is /dev/mmcblk0"
fi
rootfs=${emmc}p2

#
# Check the unique die ID so install knows which device to use
#
for arg in $(cat /proc/cmdline); do
	if echo $arg | grep omap_dieid= > /dev/null; then
		omap_dieid=$(echo $arg | sed -e s/omap_dieid=//)
	fi
done

start_usb $emmc $omap_dieid

while [ 1 ]; do
	setsid sh -c 'exec sh </dev/ttyGS0 >/dev/ttyGS0 2>&1'
done &

if echo $@ | grep really_install > /dev/null 2>&1; then

	if check_block_device $emmc; then
		blink_leds yellow 1600 400
	else
		blink_leds red 600 400
	fi

	echo "Waiting in install mode, console at ttyACM..."
	setsid cttyhack sh
else
	blink_leds magenta 150 850

	echo "Waiting in recovery mode, console at ttyACM..."

	echo "wipek.sh erases /boot kernel,"
	#echo "touch /flag;exit resumes normal boot,"
	echo "or copy to rootfs via USB file store"

	# from http://www.busybox.net/FAQ.html#job_control
	setsid cttyhack sh

	if [ '' -a -f /flag ]; then
		# fix: systemd does not start correctly here; maybe due to gadget cleanup bug
		echo "Removing usb gadget"
		kill % # stop agetty
		sleep 1
		rm -rf /sys/kernel/config/usb_gadget/g1
		modprobe -r omap2430 phy_twl4030_usb musb_hdrc

		if mount $rootfs /new_root; then
			kver=$(uname -r)
			if [ ! -d /new_root/lib/modules/$kver \
			    -a -d /new_root/lib/modules/factory/$kver ]; then
				ln -s factory/$kver /new_root/lib/modules/$kver
			fi

			if [ -d /new_root/lib/modules/$kver ]; then
				blink_leds none
				#umount /dev/pts /dev
				#umount /proc
				#umount /sys/kernel/config /sys

				echo "Starting /sbin/init on $rootfs..."
				exec env -i "TERM=$TERM" \
				  /usr/bin/switch_root /new_root /sbin/init "$@"
			else
				echo "Modules for $kver not found"
			fi
		else
			echo "Could not mount $rootfs"
		fi
		setsid cttyhack sh
	fi
	poweroff
fi

